os:
  - osx
language: objective-c
python:
    - "2.7"
before_install:
  - brew update
  - brew outdated xctool || brew upgrade xctool
  - brew install wxpython
  - brew install brew-pip
  - brew pip install pyinstaller
  - mkdir -p /Users/travis/Library/Python/2.7/lib/python/site-packages
  - echo 'import site; site.addsitedir("/usr/local/lib/python2.7/site-packages")' >> /Users/travis/Library/Python/2.7/lib/python/site-packages/homebrew.pth


install: true

