os:
- osx
language: objective-c
python:
- '2.7'
before_install:
- which python
- brew update
- brew outdated xctool || brew upgrade xctool
- brew install python --framework 
- which python
- VERSIONER_PYTHON_PREFER_32_BIT=yes arch -i386 /usr/local/opt/python/bin/python2.7
- which python
- brew install wxpython
- python -c "import wx; print wx.__version__"
- pip install -U py2app
- pip install pyinstaller
- pyinstaller --noconsole --onefile hw.py
- ls
- ls dist/
- hdiutil create dist/hw.dmg -srcfolder dist/ -ov
#- zip -r dist/macapp.zip dist/macapp.app
install: true
deploy:
  skip_cleanup: true
  provider: releases
  api_key:
    secure: VK1oVWQCRomgcFNVua00B3YSsotezzU1p6/fh73/0vwQFzVMolVnAsnfSq6EAwIcJvakU0TI9pqZR+0S3PKnUs+Kn3Ar8OwQ88t2azZNwewBfKua3tM2/7BF4y7O0gOtN1F29Yxyu0zPInIVY17BqGygibQ1kthBTm+tj3YyNW8=
  file: 
    - "dist/hw"
    - "dist/hw.dmg"
    #- "dist/macapp.zip"
  on:
    tags: true
    all_branches: true
    repo: BjornFJohansson/macapp


# http://stackoverflow.com/questions/25961639/where-is-travis-ci-expecting-the-artifacts-on-deployment
# http://stackoverflow.com/questions/19607894/how-to-get-travis-ci-to-build-and-test-xcode-projects-hosted-on-github
# https://travis-ci.org/chrissearle/web-hello-world
# http://pythonhosted.org/PyInstaller/#options-for-mac-os-x-apps
# hdiutil create ./dist/FileExplorer.dmg -srcfolder ./dist/ -ov
# http://munkymorgy.blogspot.pt/2009/01/create-dmg-files-from-command-line.html
